### ISSUE TITLE
/search/csv => AttributeError: 'bytes' object has no attribute 'encode'

### ISSUE THREAD

**Issue by panglose** [etalab/addok-docker#41]
Bonjour, lorsque je fais une requête avec l'api /seach/csv avec l'image docker j'obtiens l'erreur suivante:

 2024-11-16 16:21:36 [FALCON] [ERROR] POST /search/csv => Traceback (most recent call last):
addok-1        |   File "/usr/local/lib/python3.10/site-packages/falcon/app.py", line 323, in __call__
addok-1        |     process_request(req, resp)
addok-1        |   File "/usr/local/lib/python3.10/site-packages/falcon_multipart/middleware.py", line 57, in process_request
addok-1        |     req._params[key] = self.parse_field(form[key])
addok-1        |   File "/usr/local/lib/python3.10/site-packages/falcon_multipart/middleware.py", line 31, in parse_field
addok-1        |     field.file = BytesIO(field.file.read().encode(encoding))
**addok-1        | AttributeError: 'bytes' object has no attribute 'encode'**

Par ailleurs la même requête fonctionne bien lorsque je n'utilise pas l'image docker mais directement le site officiel

**Comment by jdesboeufs** [comment]
Bonjour,

Le site officiel utilise le dépôt https://github.com/livingdata-co/addok-server

Le présent dépôt n'est plus maintenu.

Cordialement

**Comment by panglose** [comment]
Ok je vais essayer le nouveau dépôt, merci pour l'information.
